# Generated by Django 3.1.5 on 2021-01-12 00:29

import app.models.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets')),
                ('months', models.IntegerField(default=0, validators=[app.models.validators.months_value_validator])),
                ('type', models.CharField(choices=[('Dog', 'dog'), ('Cat', 'cat'), ('Bird', 'bird'), ('Other', 'other')], max_length=10)),
                ('breed', models.CharField(default='Unknown', max_length=20)),
                ('gender', models.CharField(choices=[('Female', 'female'), ('Male', 'male')], default='Male', max_length=10)),
                ('description', models.TextField()),
                ('location', models.CharField(default='Sofia', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[app.models.validators.contains_only_digits])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
