# Generated by Django 3.1.4 on 2020-12-10 21:43

import app.models.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Pets')),
                ('months', models.PositiveIntegerField(default=0, validators=[app.models.validators.min_months_value, app.models.validators.max_months_value])),
                ('type', models.CharField(choices=[('Dog', 'dog'), ('Cat', 'cat'), ('Bird', 'bird'), ('Other', 'other')], max_length=10)),
                ('breed', models.CharField(default='Unknown', max_length=30)),
                ('gender', models.CharField(choices=[('Female', 'female'), ('Male', 'male')], default='Male', max_length=10)),
                ('description', models.TextField(default=' ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[app.models.validators.contains_only_digits])),
                ('profile_pic', models.ImageField(default='static/Default_profile_picture.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
