# Generated by Django 3.1.4 on 2020-12-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('Dog', 'dog'), ('Cat', 'cat'), ('Bird', 'bird'), ('Other', 'other')], max_length=10),
        ),
    ]
