# Generated by Django 3.1.4 on 2020-12-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_pet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], default='Male', max_length=10),
        ),
    ]
