# Generated by Django 3.1.4 on 2020-12-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_extenduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='profile_pic',
            field=models.ImageField(default='static/Default_profile_picture.png', upload_to='profile_pics'),
        ),
    ]
