# Generated by Django 3.1.4 on 2020-12-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201220_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(),
        ),
    ]
