# Generated by Django 3.1.4 on 2020-12-09 23:55

import app.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201210_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[app.models.validators.contains_only_digits]),
        ),
    ]
