# Generated by Django 3.1.4 on 2020-12-20 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201220_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='profile_pic',
        ),
    ]
